name: SonarQube Scan
run-name: ${{ github.actor }} is running the workflow for Workspace services
on:
  push:
    branches: [ "release" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  sonar-scan:
    runs-on: bynder-arc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run SonarQube Scan
        uses: bynder/github-actions/actions/sonarqube@master
